apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
  namespace: url-shortener
type: Opaque
stringData:
  # Add any sensitive data here
  # DB_PASS: "your-redis-password-if-needed"
  # Add other secrets as needed

